import { z } from "zod";

export const templateVariableSchema = z.object({
  key: z.string().regex(/^[a-z][A-Za-z0-9]*$/),
  label: z.string().min(2),
  kind: z.enum(["text", "number", "url"]),
  defaultValue: z.string(),
  help: z.string().min(3),
  required: z.boolean().default(true),
});

export const templateAssetSchema = z.object({
  channel: z.string().min(2),
  type: z.string().min(2),
  title: z.string().min(3),
  body: z.string().min(10),
  dayOffset: z.number().int().min(0),
  hour: z.number().int().min(0).max(23).default(14),
});

export const campaignTemplateSchema = z.object({
  id: z.string().min(3),
  slug: z.string().regex(/^[a-z0-9-]+$/),
  name: z.string().min(3),
  description: z.string().min(10),
  category: z.enum(["Seasonal", "Lifecycle", "Launch", "Demand generation"]),
  occasion: z.string().min(3),
  badge: z.string().min(2),
  featured: z.boolean(),
  durationDays: z.number().int().min(1),
  channels: z.array(z.string()).min(1),
  audience: z.string().min(3),
  objective: z.string().min(3),
  offer: z.string().min(3),
  variables: z.array(templateVariableSchema),
  assets: z.array(templateAssetSchema).min(1),
  topics: z.array(z.string()).min(2),
  successMetrics: z.array(z.string()).min(1),
  recommendedBudget: z.number().int().min(0),
  updatedAt: z.string(),
});

export type CampaignTemplate = z.infer<typeof campaignTemplateSchema>;
export type CampaignTemplateAsset = z.infer<typeof templateAssetSchema>;
export type TemplateVariable = z.infer<typeof templateVariableSchema>;

const updatedAt = "2026-08-15T12:00:00.000Z";
const variable = (
  key: string,
  label: string,
  defaultValue: string,
  help: string,
  kind: "text" | "number" | "url" = "text",
) => ({ key, label, defaultValue, help, kind, required: true });

const asset = (
  channel: string,
  type: string,
  title: string,
  body: string,
  dayOffset: number,
  hour = 14,
) => ({ channel, type, title, body, dayOffset, hour });

export const seededCampaignTemplates: CampaignTemplate[] = [
  {
    id: "template-product-content-showcase",
    slug: "product-content-showcase",
    name: "Product Content Showcase",
    description:
      "A visual product campaign with ready-to-review social, email, SMS, paid, and ChatGPT Ads creative.",
    category: "Launch",
    occasion: "Product campaign",
    badge: "Visual-first",
    featured: true,
    durationDays: 14,
    channels: [
      "Instagram",
      "Facebook",
      "TikTok",
      "Email",
      "SMS",
      "Meta Ads",
      "ChatGPT Ads",
      "Reddit Ads",
      "LinkedIn",
    ],
    audience:
      "Customers and prospects most likely to benefit from {{productName}}",
    objective:
      "Show {{productName}} in context and convert product interest into qualified action",
    offer: "{{offer}} for {{productName}}",
    variables: [
      variable(
        "productName",
        "Product name",
        "Your product",
        "The uploaded product or service featured in every asset.",
      ),
      variable(
        "productBenefit",
        "Primary benefit",
        "Turn scattered customer signals into one clear next action",
        "The most important outcome the product creates.",
      ),
      variable(
        "productPrice",
        "Price or plan",
        "$49 per month",
        "Price, starting price, or plan name shown where relevant.",
      ),
      variable(
        "offer",
        "Offer",
        "Try it free for 14 days",
        "The product promotion or reason to act now.",
      ),
      variable(
        "productUrl",
        "Product URL",
        "https://example.com/product",
        "The destination used by buttons and links.",
        "url",
      ),
      variable(
        "primaryCta",
        "Primary CTA",
        "See the product",
        "The action repeated across the campaign.",
      ),
    ],
    assets: [
      asset(
        "Instagram",
        "Carousel · 4 slides",
        "Meet {{productName}}",
        "Slide 1 — Meet {{productName}}\nSlide 2 — The problem: too many signals, no clear next move\nSlide 3 — The benefit: {{productBenefit}}\nSlide 4 — {{offer}} · {{primaryCta}}",
        0,
        12,
      ),
      asset(
        "Instagram",
        "Reel · 15 seconds",
        "From signal overload to a clear next move",
        "Scene 1 — Hook: Your data is not the problem\nScene 2 — Product: Show {{productName}} using the uploaded product visual\nScene 3 — Benefit: {{productBenefit}}\nScene 4 — End card: {{offer}} · {{primaryCta}}",
        2,
        17,
      ),
      asset(
        "Facebook",
        "Product post",
        "A clearer next move starts here",
        "Meet {{productName}} from {{brandName}}. {{productBenefit}}. Get {{offer}} at {{productUrl}}.",
        3,
        11,
      ),
      asset(
        "TikTok",
        "Short-form video · 18 seconds",
        "POV: your customer data finally tells you what to do",
        "Scene 1 — POV hook with the problem on screen\nScene 2 — Screen recording of {{productName}}\nScene 3 — Before and after: scattered signals → {{productBenefit}}\nScene 4 — Creator CTA: {{primaryCta}} · {{offer}}",
        4,
        18,
      ),
      asset(
        "Email",
        "Product launch email",
        "Introducing {{productName}}: a clearer way forward",
        "Hi {{firstName}},\n\nMeet {{productName}}—built to help your team {{productBenefit}}. It is available for {{productPrice}}, and right now you can {{offer}}.\n\n{{primaryCta}}: {{productUrl}}",
        5,
        10,
      ),
      asset(
        "SMS",
        "Product reminder",
        "Your {{productName}} invitation",
        "{{brandName}}: {{productName}} helps you {{productBenefit}}. {{offer}}: {{productUrl}} Reply STOP to opt out.",
        8,
        14,
      ),
      asset(
        "Meta Ads",
        "Product ad",
        "Your next growth move, made clear",
        "Use {{productName}} to {{productBenefit}}. {{offer}} from {{brandName}}. {{primaryCta}}.",
        6,
        15,
      ),
      asset(
        "ChatGPT Ads",
        "Chat card ad",
        "Meet {{productName}}",
        "{{productBenefit}}. {{offer}}.",
        6,
        15,
      ),
      asset(
        "Reddit Ads",
        "Sponsored text post",
        "What changed when we tried {{productName}}",
        "We built {{productName}} for teams that need to {{productBenefit}}. {{offer}} — ask us anything about how it works.",
        7,
        14,
      ),
      asset(
        "LinkedIn",
        "Founder post",
        "Why we built {{productName}}",
        "Teams rarely need more data. They need a clearer decision. We built {{productName}} to {{productBenefit}}. Today, {{brandName}} is opening access with this offer: {{offer}}.",
        10,
        9,
      ),
    ],
    topics: [
      "The customer problem behind {{productName}}",
      "Product experience and proof",
      "A clear product offer",
    ],
    successMetrics: [
      "Product page visits",
      "Trial or purchase conversions",
      "Creative saves and shares",
    ],
    recommendedBudget: 3500,
    updatedAt: "2026-08-16T16:00:00.000Z",
  },
  {
    id: "template-halloween",
    slug: "halloween-night-shift",
    name: "Halloween Night Shift",
    description:
      "A playful but credible seasonal campaign that builds intrigue, launches an offer, and closes with a time-boxed final call.",
    category: "Seasonal",
    occasion: "Halloween",
    badge: "October 31",
    featured: true,
    durationDays: 18,
    channels: ["Email", "Instagram", "LinkedIn", "Meta Ads"],
    audience: "Prospects and engaged subscribers who have not converted",
    objective: "Convert seasonal attention into qualified pipeline",
    offer: "{{offerName}} with {{discount}}",
    variables: [
      variable(
        "offerName",
        "Offer name",
        "The Midnight Growth Audit",
        "The seasonal offer customers receive.",
      ),
      variable(
        "discount",
        "Promotion",
        "20% off",
        "Discount or bonus language.",
      ),
      variable(
        "deadline",
        "Deadline",
        "October 31 at midnight",
        "When the offer expires.",
      ),
      variable(
        "primaryCta",
        "Primary CTA",
        "Claim your audit",
        "The action used across the bundle.",
      ),
    ],
    assets: [
      asset(
        "Email",
        "Teaser email",
        "Something useful is lurking in your funnel",
        "The scariest growth problems are the ones hiding in plain sight. {{brandName}} is opening early access to {{offerName}}—a practical way to find the signals your team may be missing.",
        0,
        10,
      ),
      asset(
        "Instagram",
        "Organic post",
        "Do not let good signals disappear",
        "Your customer journey has clues. This Halloween, {{brandName}} is helping teams uncover them with {{offerName}}. {{primaryCta}} before {{deadline}}.",
        1,
        13,
      ),
      asset(
        "LinkedIn",
        "Organic post",
        "The hidden cost of an unclear customer journey",
        "Most teams are not short on data. They are short on a clear next move. For Halloween, {{brandName}} is offering {{offerName}} with {{discount}} until {{deadline}}.",
        3,
        9,
      ),
      asset(
        "Meta Ads",
        "Paid ad · curiosity",
        "What is hiding in your funnel?",
        "Find the customer signals your team is missing. Get {{offerName}} from {{brandName}} with {{discount}} before {{deadline}}.",
        3,
        15,
      ),
      asset(
        "Email",
        "Launch email",
        "The Halloween offer is live",
        "{{offerName}} is now available with {{discount}}. See the signals shaping your customer journey and leave with a focused action plan. {{primaryCta}} before {{deadline}}.",
        5,
        10,
      ),
      asset(
        "Instagram",
        "Story sequence",
        "Three signals worth checking",
        "Frame 1: Where do trials stall? Frame 2: Which accounts show intent? Frame 3: What should your team do next? {{primaryCta}} with {{brandName}}.",
        8,
        16,
      ),
      asset(
        "Meta Ads",
        "Paid ad · urgency",
        "Do not ghost your best opportunities",
        "{{offerName}} ends {{deadline}}. Turn the signals already in your data into a practical next move with {{brandName}}.",
        12,
        12,
      ),
      asset(
        "Email",
        "Last-chance email",
        "Last call before midnight",
        "Your Halloween window for {{offerName}} and {{discount}} closes {{deadline}}. If a clearer growth plan is on your list, now is the time to {{primaryCta}}.",
        17,
        15,
      ),
    ],
    topics: [
      "Hidden growth signals",
      "Customer journey clarity",
      "Seasonal urgency",
    ],
    successMetrics: [
      "Qualified offer conversions",
      "Email click-through rate",
      "Paid cost per lead",
    ],
    recommendedBudget: 1800,
    updatedAt,
  },
  {
    id: "template-bfcm",
    slug: "bfcm-revenue-sprint",
    name: "BFCM Revenue Sprint",
    description:
      "A complete Black Friday–Cyber Monday program with early access, launch, retargeting, urgency, and post-event follow-up.",
    category: "Seasonal",
    occasion: "BFCM",
    badge: "Black Friday → Cyber Monday",
    featured: true,
    durationDays: 28,
    channels: ["Email", "Instagram", "LinkedIn", "Meta Ads", "Google Ads"],
    audience: "High-intent prospects, engaged trials, and dormant evaluators",
    objective:
      "Maximize qualified BFCM conversions without eroding brand trust",
    offer: "{{discount}} on {{offerName}}",
    variables: [
      variable(
        "offerName",
        "Offer name",
        "Northstar Growth Plan",
        "Product, package, or service promoted.",
      ),
      variable(
        "discount",
        "Promotion",
        "30% off annual plans",
        "Discount or value-add offer.",
      ),
      variable(
        "deadline",
        "Final deadline",
        "Cyber Monday at 11:59 PM",
        "The final conversion deadline.",
      ),
      variable(
        "primaryCta",
        "Primary CTA",
        "Unlock the offer",
        "The campaign-wide call to action.",
      ),
    ],
    assets: [
      asset(
        "Email",
        "VIP early-access email",
        "Your BFCM early access starts now",
        "You are getting the first look at {{discount}} on {{offerName}} from {{brandName}}. Get ahead of the rush and {{primaryCta}} today.",
        0,
        9,
      ),
      asset(
        "LinkedIn",
        "Organic post",
        "A better BFCM decision starts with clarity",
        "BFCM does not need to mean louder marketing. {{brandName}} is making {{offerName}} available with {{discount}} so teams can act on customer signals with more confidence.",
        2,
        10,
      ),
      asset(
        "Instagram",
        "Carousel",
        "Five growth signals to use before BFCM",
        "A five-frame educational carousel covering intent, activation, retention, expansion, and the next best action—ending with {{discount}} on {{offerName}}.",
        4,
        13,
      ),
      asset(
        "Meta Ads",
        "Paid ad · value",
        "Make every customer signal useful",
        "Get {{discount}} on {{offerName}} and turn fragmented customer data into a focused next move. {{primaryCta}} with {{brandName}}.",
        5,
        15,
      ),
      asset(
        "Google Ads",
        "Search ad",
        "{{offerName}} | {{discount}}",
        "BFCM offer from {{brandName}}. See the customer journey clearly and turn insight into action. Available until {{deadline}}.",
        7,
        11,
      ),
      asset(
        "Email",
        "Black Friday launch",
        "Black Friday: {{discount}} is live",
        "The wait is over. {{discount}} on {{offerName}} is live now. Bring your customer signals together, find the opportunity, and {{primaryCta}} before {{deadline}}.",
        10,
        8,
      ),
      asset(
        "Instagram",
        "Reel script",
        "From scattered signals to one next move",
        "Open on three disconnected dashboards. Transition to one clear customer journey. Close on {{discount}} for {{offerName}} and the CTA: {{primaryCta}}.",
        11,
        17,
      ),
      asset(
        "Meta Ads",
        "Paid ad · proof",
        "Clarity compounds",
        "Growth teams use {{brandName}} to see where customers get stuck and what to do next. This BFCM, get {{offerName}} with {{discount}}.",
        14,
        12,
      ),
      asset(
        "Email",
        "Cyber Monday urgency",
        "Cyber Monday ends tonight",
        "This is the final day to get {{discount}} on {{offerName}}. If clearer growth decisions are on your roadmap, {{primaryCta}} before {{deadline}}.",
        20,
        9,
      ),
      asset(
        "Meta Ads",
        "Retargeting ad",
        "Still deciding? Your offer is waiting",
        "Return to {{offerName}} from {{brandName}} and secure {{discount}} before {{deadline}}.",
        20,
        14,
      ),
      asset(
        "Email",
        "Post-event follow-up",
        "Missed BFCM? Start with the signal review",
        "The BFCM window has closed, but the opportunity in your customer data has not. Book a practical signal review with {{brandName}} and leave with a clearer next move.",
        24,
        10,
      ),
    ],
    topics: ["BFCM value", "Customer signal clarity", "Responsible urgency"],
    successMetrics: [
      "BFCM conversions",
      "Blended acquisition cost",
      "Incremental pipeline",
    ],
    recommendedBudget: 7500,
    updatedAt,
  },
  {
    id: "template-black-friday",
    slug: "black-friday-flash-sale",
    name: "Black Friday Flash Sale",
    description:
      "A focused Black Friday launch for teams that need a shorter promotional window and a clear conversion arc.",
    category: "Seasonal",
    occasion: "Black Friday",
    badge: "November 27",
    featured: true,
    durationDays: 14,
    channels: ["Email", "Instagram", "Meta Ads", "Google Ads"],
    audience: "High-intent prospects and returning website visitors",
    objective: "Create a concentrated Black Friday conversion spike",
    offer: "{{discount}} on {{offerName}}",
    variables: [
      variable(
        "offerName",
        "Offer name",
        "Northstar Annual",
        "The promoted product or plan.",
      ),
      variable(
        "discount",
        "Promotion",
        "25% off",
        "The Black Friday incentive.",
      ),
      variable(
        "deadline",
        "Deadline",
        "Friday at 11:59 PM",
        "When the flash sale closes.",
      ),
      variable(
        "primaryCta",
        "Primary CTA",
        "Get the Black Friday offer",
        "Primary action language.",
      ),
    ],
    assets: [
      asset(
        "Email",
        "Preview email",
        "A clearer Black Friday offer is coming",
        "{{brandName}} is preparing {{discount}} on {{offerName}} for teams ready to turn customer signals into action. Watch your inbox for access.",
        0,
        10,
      ),
      asset(
        "Instagram",
        "Countdown post",
        "Three days to Black Friday",
        "A focused offer for a focused next move: {{discount}} on {{offerName}} from {{brandName}}. Starts soon.",
        2,
        16,
      ),
      asset(
        "Meta Ads",
        "Paid ad · preview",
        "Black Friday clarity is coming",
        "Be first to access {{discount}} on {{offerName}} and find a clearer path from customer signal to growth action.",
        2,
        14,
      ),
      asset(
        "Email",
        "Launch email",
        "Black Friday starts now: {{discount}}",
        "{{discount}} on {{offerName}} is live. See the full customer journey, identify the opportunity, and {{primaryCta}} before {{deadline}}.",
        5,
        8,
      ),
      asset(
        "Google Ads",
        "Search ad",
        "Black Friday {{offerName}} Offer",
        "Get {{discount}} from {{brandName}}. Turn customer data into clear growth action. Ends {{deadline}}.",
        5,
        9,
      ),
      asset(
        "Instagram",
        "Offer post",
        "The Black Friday offer is live",
        "{{discount}} on {{offerName}}. No noise—just a clearer way to see the signal and choose the next move. {{primaryCta}}.",
        6,
        13,
      ),
      asset(
        "Meta Ads",
        "Retargeting ad",
        "Your Black Friday offer ends soon",
        "Come back to {{offerName}} and secure {{discount}} before {{deadline}}.",
        9,
        17,
      ),
      asset(
        "Email",
        "Final-hours email",
        "Final hours: Black Friday ends tonight",
        "The window for {{discount}} on {{offerName}} closes {{deadline}}. {{primaryCta}} while the offer is still available.",
        13,
        16,
      ),
    ],
    topics: [
      "Black Friday offer",
      "Focused growth action",
      "Final-hours urgency",
    ],
    successMetrics: [
      "Offer conversion rate",
      "Revenue per recipient",
      "Retargeting return",
    ],
    recommendedBudget: 4200,
    updatedAt,
  },
  {
    id: "template-cyber-monday",
    slug: "cyber-monday-conversion-push",
    name: "Cyber Monday Conversion Push",
    description:
      "A compact digital-first campaign for converting evaluators and retargeting visitors before the Cyber Monday cutoff.",
    category: "Seasonal",
    occasion: "Cyber Monday",
    badge: "November 30",
    featured: false,
    durationDays: 10,
    channels: ["Email", "Instagram", "Meta Ads", "Google Ads"],
    audience:
      "Recent site visitors, abandoned evaluations, and engaged subscribers",
    objective: "Convert high-intent digital audiences during Cyber Monday",
    offer: "{{discount}} on {{offerName}}",
    variables: [
      variable(
        "offerName",
        "Offer name",
        "Northstar Pro",
        "The product or plan promoted.",
      ),
      variable("discount", "Promotion", "30% off", "Cyber Monday incentive."),
      variable(
        "deadline",
        "Deadline",
        "Monday at 11:59 PM",
        "Offer expiry language.",
      ),
      variable(
        "primaryCta",
        "Primary CTA",
        "Activate the offer",
        "Primary conversion action.",
      ),
    ],
    assets: [
      asset(
        "Email",
        "Sunday preview",
        "Cyber Monday access opens tomorrow",
        "Tomorrow, {{brandName}} opens {{discount}} on {{offerName}}. Get ready to turn the signals in your customer journey into a clearer growth plan.",
        0,
        12,
      ),
      asset(
        "Google Ads",
        "Search ad",
        "Cyber Monday {{offerName}}",
        "Get {{discount}} from {{brandName}} through {{deadline}}. A clearer way to move from signal to action.",
        1,
        8,
      ),
      asset(
        "Email",
        "Launch email",
        "Cyber Monday is live",
        "{{discount}} on {{offerName}} is available now. {{primaryCta}} and give your team a clearer next move before {{deadline}}.",
        1,
        9,
      ),
      asset(
        "Meta Ads",
        "Retargeting ad",
        "Your Cyber Monday offer is live",
        "Return to {{offerName}} and get {{discount}} before {{deadline}}. {{primaryCta}} with {{brandName}}.",
        1,
        11,
      ),
      asset(
        "Instagram",
        "Story sequence",
        "Cyber Monday in three frames",
        "Signal. Decision. Action. Bring them together with {{offerName}} from {{brandName}}—now {{discount}} until {{deadline}}.",
        1,
        15,
      ),
      asset(
        "Email",
        "Final-hours email",
        "Four hours left on {{offerName}}",
        "Cyber Monday ends {{deadline}}. This is your final opportunity to get {{discount}} and {{primaryCta}}.",
        2,
        18,
      ),
      asset(
        "Meta Ads",
        "Final-hours ad",
        "Ends tonight",
        "{{discount}} on {{offerName}} ends {{deadline}}. Turn customer signals into a clear next move today.",
        2,
        19,
      ),
    ],
    topics: [
      "Digital urgency",
      "High-intent retargeting",
      "Customer signal action",
    ],
    successMetrics: [
      "Same-day conversions",
      "Retargeting CPA",
      "Search conversion rate",
    ],
    recommendedBudget: 3000,
    updatedAt,
  },
  {
    id: "template-holiday-guide",
    slug: "holiday-gift-guide",
    name: "Holiday Gift Guide",
    description:
      "An educational holiday campaign that packages offers into useful recommendations instead of relying only on discount pressure.",
    category: "Seasonal",
    occasion: "Holiday season",
    badge: "November–December",
    featured: false,
    durationDays: 28,
    channels: ["Email", "Instagram", "LinkedIn", "Meta Ads", "Blog"],
    audience: "Prospects comparing options and customers considering expansion",
    objective:
      "Create qualified holiday demand with useful, giftable recommendations",
    offer: "{{offerName}} for {{audienceName}}",
    variables: [
      variable(
        "offerName",
        "Featured offer",
        "The Growth Team Gift Guide",
        "The guide, collection, or package.",
      ),
      variable(
        "audienceName",
        "Audience label",
        "ambitious growth teams",
        "Who the guide is designed for.",
      ),
      variable(
        "deadline",
        "Seasonal deadline",
        "December 18",
        "Planning or shipping deadline.",
      ),
      variable(
        "primaryCta",
        "Primary CTA",
        "Explore the guide",
        "The campaign-wide call to action.",
      ),
    ],
    assets: [
      asset(
        "Blog",
        "Guide outline",
        "{{offerName}}",
        "Create a practical guide for {{audienceName}} organized around clarity, better decisions, and faster action. Include a recommendation checklist and a direct path to {{primaryCta}}.",
        0,
        10,
      ),
      asset(
        "Email",
        "Guide launch",
        "A useful holiday guide for {{audienceName}}",
        "{{brandName}} created {{offerName}} to help {{audienceName}} choose tools and practices that create clarity all year. {{primaryCta}} before {{deadline}}.",
        2,
        9,
      ),
      asset(
        "Instagram",
        "Carousel",
        "Five gifts for a clearer growth year",
        "A five-frame carousel featuring practical growth-team recommendations from {{offerName}}, ending with {{primaryCta}}.",
        4,
        13,
      ),
      asset(
        "LinkedIn",
        "Organic post",
        "The best growth gift is a clearer decision",
        "This season, {{brandName}} assembled {{offerName}} for {{audienceName}}—useful recommendations that keep working after the holidays.",
        6,
        10,
      ),
      asset(
        "Meta Ads",
        "Paid ad",
        "A holiday guide built for growth teams",
        "Explore {{offerName}} from {{brandName}} and find a more useful way to plan the next growth move.",
        8,
        15,
      ),
      asset(
        "Email",
        "Recommendation email",
        "Three picks from {{offerName}}",
        "Start with the three recommendations most likely to help {{audienceName}} see the signal, align the team, and act with confidence. {{primaryCta}}.",
        13,
        10,
      ),
      asset(
        "Instagram",
        "Reminder post",
        "Still planning for next year?",
        "Use {{offerName}} from {{brandName}} to give your team a clearer starting point before {{deadline}}.",
        19,
        16,
      ),
      asset(
        "Email",
        "Deadline email",
        "Last call for the holiday guide",
        "If {{offerName}} is part of your year-end planning, {{primaryCta}} before {{deadline}} and start the new year with a clearer next move.",
        26,
        11,
      ),
    ],
    topics: ["Useful recommendations", "Year-end planning", "Team clarity"],
    successMetrics: [
      "Guide engagement",
      "Qualified CTA clicks",
      "Assisted pipeline",
    ],
    recommendedBudget: 2200,
    updatedAt,
  },
  {
    id: "template-product-launch",
    slug: "product-launch-command-center",
    name: "Product Launch Command Center",
    description:
      "A coordinated launch sequence that moves from problem education to announcement, proof, retargeting, and adoption follow-up.",
    category: "Launch",
    occasion: "Product launch",
    badge: "Evergreen",
    featured: true,
    durationDays: 21,
    channels: [
      "Email",
      "LinkedIn",
      "Instagram",
      "Meta Ads",
      "Google Ads",
      "ChatGPT Ads",
      "Reddit Ads",
      "Blog",
    ],
    audience: "Prospects and customers affected by the product problem",
    objective: "Create awareness, qualified demand, and early product adoption",
    offer: "Early access to {{productName}}",
    variables: [
      variable(
        "productName",
        "Product name",
        "Journey Signals",
        "The feature, product, or package being launched.",
      ),
      variable(
        "customerProblem",
        "Customer problem",
        "fragmented customer signals",
        "The problem the launch resolves.",
      ),
      variable(
        "proofPoint",
        "Proof point",
        "find growth opportunities in minutes",
        "A credible outcome or product proof.",
      ),
      variable(
        "primaryCta",
        "Primary CTA",
        "Book a product walkthrough",
        "Primary launch action.",
      ),
      variable(
        "productUrl",
        "Product URL",
        "https://example.com/product",
        "The landing page opened from the ChatGPT ad.",
        "url",
      ),
    ],
    assets: [
      asset(
        "Blog",
        "Launch article",
        "Introducing {{productName}}",
        "Explain why {{customerProblem}} slows teams down, how {{productName}} creates a clearer path forward, and how customers can {{proofPoint}}.",
        0,
        9,
      ),
      asset(
        "Email",
        "Problem email",
        "The signal is there. The next move is not.",
        "When {{customerProblem}} gets in the way, good opportunities sit unnoticed. {{brandName}} built {{productName}} to create a clearer path from signal to action.",
        1,
        10,
      ),
      asset(
        "LinkedIn",
        "Founder post",
        "Why we built {{productName}}",
        "We kept hearing the same problem: {{customerProblem}}. {{productName}} helps teams {{proofPoint}}—without adding another disconnected dashboard.",
        3,
        9,
      ),
      asset(
        "Instagram",
        "Teaser carousel",
        "A clearer next move is coming",
        "Use three frames to show the problem, the signal, and the promise of {{productName}}. End with launch-day anticipation.",
        4,
        14,
      ),
      asset(
        "Email",
        "Launch announcement",
        "Meet {{productName}}",
        "{{productName}} is live. See the full customer journey, identify the opportunity, and {{proofPoint}} with {{brandName}}. {{primaryCta}}.",
        7,
        9,
      ),
      asset(
        "Meta Ads",
        "Paid launch ad",
        "Meet {{productName}}",
        "Move beyond {{customerProblem}}. Use {{productName}} from {{brandName}} to {{proofPoint}}. {{primaryCta}}.",
        7,
        13,
      ),
      asset(
        "Google Ads",
        "Search ad",
        "{{productName}} by {{brandName}}",
        "Solve {{customerProblem}} and {{proofPoint}}. Explore the new product and {{primaryCta}}.",
        8,
        11,
      ),
      asset(
        "ChatGPT Ads",
        "Chat card ad",
        "Meet {{productName}}",
        "Solve {{customerProblem}} and {{proofPoint}} with {{productName}}.",
        8,
        11,
      ),
      asset(
        "Reddit Ads",
        "Sponsored text post",
        "We built {{productName}} to solve {{customerProblem}}",
        "After hearing the same problem from growing teams, we built {{productName}} so they can {{proofPoint}}. Here is what changed and what we learned.",
        9,
        14,
      ),
      asset(
        "LinkedIn",
        "Proof post",
        "From signal to action with {{productName}}",
        "Show the before-and-after workflow: disconnected signals, one customer journey, and a focused next move. Then invite teams to {{primaryCta}}.",
        12,
        10,
      ),
      asset(
        "Email",
        "Adoption follow-up",
        "Your first move with {{productName}}",
        "Start with one customer question, connect the signal, and use {{productName}} to choose the next action. Need help? {{primaryCta}}.",
        18,
        10,
      ),
    ],
    topics: ["Customer problem", "Product announcement", "Proof and adoption"],
    successMetrics: [
      "Qualified demos",
      "Product activation",
      "Launch-influenced pipeline",
    ],
    recommendedBudget: 6000,
    updatedAt,
  },
  {
    id: "template-webinar",
    slug: "webinar-registration-engine",
    name: "Webinar Registration Engine",
    description:
      "A registration and attendance sequence with expert positioning, reminders, live-event urgency, and replay follow-up.",
    category: "Demand generation",
    occasion: "Webinar",
    badge: "Evergreen",
    featured: false,
    durationDays: 18,
    channels: ["Email", "LinkedIn", "Instagram", "Meta Ads"],
    audience: "Prospects who match the webinar problem and customer profile",
    objective:
      "Drive qualified registrations, attendance, and post-event conversations",
    offer: "Live access to {{eventName}}",
    variables: [
      variable(
        "eventName",
        "Event name",
        "From Signal to Action",
        "The webinar or virtual event title.",
      ),
      variable(
        "eventDate",
        "Event date",
        "September 24 at 1 PM ET",
        "Human-readable live date and time.",
      ),
      variable(
        "speakerName",
        "Speaker",
        "Maya Chen",
        "Primary expert or host.",
      ),
      variable(
        "primaryCta",
        "Primary CTA",
        "Reserve your seat",
        "Registration action.",
      ),
    ],
    assets: [
      asset(
        "Email",
        "Invitation email",
        "You are invited: {{eventName}}",
        "Join {{speakerName}} and {{brandName}} on {{eventDate}} for a practical session on turning customer signals into clear marketing action. {{primaryCta}}.",
        0,
        10,
      ),
      asset(
        "LinkedIn",
        "Announcement post",
        "New live session: {{eventName}}",
        "On {{eventDate}}, {{speakerName}} will share a practical framework for moving from customer signal to focused action. {{primaryCta}} with {{brandName}}.",
        1,
        9,
      ),
      asset(
        "Meta Ads",
        "Registration ad",
        "{{eventName}}",
        "Join {{brandName}} live on {{eventDate}}. Learn how to find the signal, align the team, and choose the next action. {{primaryCta}}.",
        2,
        14,
      ),
      asset(
        "Instagram",
        "Speaker card",
        "Meet {{speakerName}}",
        "Introduce {{speakerName}}, the customer problem they will unpack, and the outcome attendees will take away from {{eventName}}.",
        4,
        13,
      ),
      asset(
        "Email",
        "Value email",
        "Three things you will learn at {{eventName}}",
        "Learn how to recognize intent, identify customer friction, and turn the strongest signal into one focused next move. Join us {{eventDate}}.",
        7,
        10,
      ),
      asset(
        "LinkedIn",
        "Reminder post",
        "One week until {{eventName}}",
        "If clearer growth decisions are on your roadmap, join {{speakerName}} and {{brandName}} on {{eventDate}}. {{primaryCta}}.",
        10,
        9,
      ),
      asset(
        "Email",
        "Day-of reminder",
        "We are live today",
        "{{eventName}} starts {{eventDate}}. Bring one customer-journey question and leave with a practical next move. Your seat is ready.",
        14,
        9,
      ),
      asset(
        "Email",
        "Replay follow-up",
        "The {{eventName}} replay is ready",
        "Watch the practical framework from {{speakerName}}, then book a short signal review with {{brandName}} to apply it to your customer journey.",
        16,
        11,
      ),
    ],
    topics: ["Expert education", "Event registration", "Replay conversion"],
    successMetrics: [
      "Qualified registrations",
      "Attendance rate",
      "Post-event meetings",
    ],
    recommendedBudget: 2400,
    updatedAt,
  },
  {
    id: "template-winback",
    slug: "customer-winback-sequence",
    name: "Customer Win-back Sequence",
    description:
      "A consent-aware lifecycle sequence for re-engaging dormant trials or customers with useful guidance and a credible reason to return.",
    category: "Lifecycle",
    occasion: "Win-back",
    badge: "Evergreen",
    featured: false,
    durationDays: 21,
    channels: ["Email", "LinkedIn", "Meta Ads"],
    audience: "Dormant trials or customers with valid marketing consent",
    objective:
      "Reactivate qualified dormant users without over-contacting them",
    offer: "{{offerName}}",
    variables: [
      variable(
        "offerName",
        "Return offer",
        "A complimentary signal review",
        "The value offered to returning users.",
      ),
      variable(
        "inactiveWindow",
        "Inactive window",
        "14 days",
        "How long the audience has been inactive.",
      ),
      variable(
        "customerOutcome",
        "Desired outcome",
        "find the next activation opportunity",
        "What returning users can accomplish.",
      ),
      variable(
        "primaryCta",
        "Primary CTA",
        "Return to your workspace",
        "Primary reactivation action.",
      ),
    ],
    assets: [
      asset(
        "Email",
        "Helpful reminder",
        "Your workspace is ready when you are",
        "You already connected the signals. Return to {{brandName}} to {{customerOutcome}} and choose a clearer next move. {{primaryCta}}.",
        0,
        10,
      ),
      asset(
        "LinkedIn",
        "Educational post",
        "What dormant journeys can teach a growth team",
        "When activity slows, the signal still matters. Look for friction, intent, and the smallest useful next action—then build from there.",
        3,
        9,
      ),
      asset(
        "Meta Ads",
        "Retargeting ad",
        "Pick up where you left off",
        "Return to {{brandName}} and {{customerOutcome}}. Your customer signals are ready when you are.",
        4,
        14,
      ),
      asset(
        "Email",
        "Value email",
        "Three signals worth checking first",
        "Start with recent intent, activation friction, and accounts closest to value. {{brandName}} can help you turn each signal into a focused next action.",
        7,
        10,
      ),
      asset(
        "Email",
        "Offer email",
        "A practical reason to return",
        "Come back to {{brandName}} for {{offerName}} and leave with a clearer plan to {{customerOutcome}}. {{primaryCta}}.",
        12,
        10,
      ),
      asset(
        "Meta Ads",
        "Offer retargeting ad",
        "A clearer next move is waiting",
        "Get {{offerName}} from {{brandName}} and {{customerOutcome}}. {{primaryCta}} today.",
        13,
        15,
      ),
      asset(
        "Email",
        "Permission close",
        "Should we close the loop?",
        "We do not want to add noise. If {{offerName}} would help you {{customerOutcome}}, {{primaryCta}}. Otherwise, we will pause this sequence.",
        20,
        10,
      ),
    ],
    topics: [
      "Useful re-engagement",
      "Activation signals",
      "Consent-aware close",
    ],
    successMetrics: [
      "Reactivation rate",
      "Qualified return sessions",
      "Unsubscribe rate",
    ],
    recommendedBudget: 1200,
    updatedAt,
  },
].map((template) => campaignTemplateSchema.parse(template));

export function renderTemplateString(
  value: string,
  variables: Record<string, string>,
) {
  return value.replace(/{{\s*([a-zA-Z0-9]+)\s*}}/g, (_, key: string) =>
    variables[key] === undefined ? `{{${key}}}` : variables[key],
  );
}

export function addTemplateDays(startDate: string, dayOffset: number) {
  const value = new Date(`${startDate}T00:00:00.000Z`);
  value.setUTCDate(value.getUTCDate() + dayOffset);
  return value.toISOString().slice(0, 10);
}

export function instantiateCampaignTemplate(
  template: CampaignTemplate,
  input: {
    brandName: string;
    startDate: string;
    variables: Record<string, string>;
  },
) {
  const defaults = Object.fromEntries(
    template.variables.map((item) => [item.key, item.defaultValue]),
  );
  const variables = {
    ...defaults,
    ...input.variables,
    brandName: input.brandName,
  };
  const render = (value: string) => renderTemplateString(value, variables);
  return {
    summary: render(template.description),
    objective: render(template.objective),
    audience: render(template.audience),
    offer: render(template.offer),
    startDate: input.startDate,
    endDate: addTemplateDays(input.startDate, template.durationDays),
    channels: template.channels,
    plan: {
      topics: template.topics.map(render),
      successMetrics: template.successMetrics.map(render),
      assumptions: [
        "Template variables and Brand Kit guidance are current",
        "All selected destination connections remain available",
      ],
      risks: [
        "Seasonal timing may require schedule adjustments",
        "Promotion language requires final reviewer approval",
      ],
      templateId: template.id,
      templateName: template.name,
      recommendedBudget: template.recommendedBudget,
      variables,
    },
    assets: template.assets.map((item) => ({
      ...item,
      title: render(item.title),
      body: render(item.body),
      scheduledAt: `${addTemplateDays(input.startDate, item.dayOffset)}T${String(item.hour).padStart(2, "0")}:00:00.000Z`,
    })),
  };
}
